### ISSUE TITLE
Ion input class 'has-value' not added with initial value

### ISSUE THREAD

**Issue by Luchillo** [driftyco/ionic2#710]
I'm using `ion-input` with floating label, which shoult make the label jump up when a value is inside the input, it does when i add it manually but when set from the component it breaks.
When i open the app in browser the `floating-label` should add the class `has-value` since i'm providing a starting value for both input:
![captura de pantalla 2015-12-09 a las 12 10 56 p m](https://cloud.githubusercontent.com/assets/9698639/11692532/f49c0486-9e6d-11e5-8d78-71110ffce7d4.png)

I have a form:
>     <form action="">
      <ion-list>
        <ion-input floating-label>
          <ion-label>Username</ion-label>
          <input type="text" [(ng-model)]='user.username' value="">
        </ion-input>
        <ion-input floating-label>
          <ion-label>Password</ion-label>
          <input type="password" [(ng-model)]='user.password' value="">
        </ion-input>
        <button (click)="login()">Button</button>
      </ion-list>
    </form>

Then there's my controller up to the constructor:
>    import {Page, NavController, Popup} from 'ionic/ionic';
import {Config} from '../services/config';
import {DB} from '../services/db';
import {GettingStartedPage} from '../getting-started/getting-started';

>     @Page({
      templateUrl: 'app/login/login.html',
    })
    export class LoginPage {
      constructor(
        private nav: NavController,
        private popup: Popup,
        private conf: Config,
        private db: DB
      ) {
        this.user = {
          username: 'asdf',
          password: '82'
        };
      }

**Comment by brandyscarney** [comment]
This is fixed in master. It will be in the next release, alpha.41, which we plan on doing later today. Please take a look at our [changelog](https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md) for some other major changes in this release.

**Comment by Luchillo** [comment]
Today monday 14/12/2015 i updated to alpha 41 and still happening, could it have to do with ngForm or my way of using it?

**Comment by brandyscarney** [comment]
I copied your code exactly as above (besides changing `ng-model` to `ngModel`) and it is working for me. Can you try updating to alpha.42? Some of the changes made didn't make it into 41.  

https://github.com/driftyco/ionic2/blob/master/CHANGELOG.md#steps-to-upgrade-to-alpha42

**Comment by Luchillo** [comment]
Sorry, bad typing, i did update to alpha.42, here's my filtered npm log for the project:
>aplicaciones2@MacBook-Pro-de-aplicacioes-2:~/Documents/Programming/OSGroup/taoappionic2$ npm list | grep ionic
taoappionic2@ /Users/aplicaciones2/Documents/Programming/OSGroup/taoappionic2
├─┬ ionic-framework@2.0.0-alpha.42

But my html changed a bit:
>     <ion-content padding class="login">
        <form (ngSubmit)='login()' #loginForm='ngForm'>
          <ion-list>
            <ion-input floating-label>
              <ion-label>Username</ion-label>
              <input type="text" class="form-control" [(ngModel)]='user.username' [ngControl]='username' required>
            </ion-input>
            <ion-input floating-label>
              <ion-label>Password</ion-label>
              <input type="password" [(ngModel)]='user.password' [ngControl]='password' required>
            </ion-input>
            <button type="submit">Login</button>
          </ion-list>
        </form>
      </ion-content>

**Comment by brandyscarney** [comment]
It seems this is happening when `ngFormModel` is missing from the HTML and/or JavaScript. Can you add `ngFormModel` for now and I'll reopen to look into this more. 

HTML:

```
  <form (ngSubmit)='login()' [ngFormModel]="myForm" #loginForm='ngForm'>
     <ion-list>
       <ion-input floating-label>
         <ion-label>Username</ion-label>
         <input type="text" class="form-control" [(ngModel)]='user.username' ngControl='username' required>
       </ion-input>
       <ion-input floating-label>
         <ion-label>Password</ion-label>
         <input type="password" [(ngModel)]='user.password' ngControl='password' required>
       </ion-input>
       <button type="submit">Login</button>
     </ion-list>
   </form>
```

JS:

```
import {App} from 'ionic/ionic';
import {FormBuilder, Validators} from 'angular2/common';


@App({
  templateUrl: 'main.html'
})
class E2EApp {
  constructor(fb: FormBuilder) {
    this.user = {
      username: 'asdf',
      password: '82'
    };

    this.myForm = fb.group({
      username: ["", Validators.required],
      password: ["", Validators.required]
    });
  }
}
```

**Comment by Luchillo** [comment]
Do i remove the brackets '[ ]' for `ngControl` in my html?

**Comment by brandyscarney** [comment]
Yes, I don't believe the brackets are needed. Haven't seen them in any form examples: https://angular.io/docs/ts/latest/guide/forms.html
